// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample-data/sample_data_service.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace KillrVideo.SampleData {
  public static class SampleDataService
  {
    static readonly string __ServiceName = "killrvideo.sample_data.SampleDataService";

    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleCommentsRequest> __Marshaller_AddSampleCommentsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleCommentsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleCommentsResponse> __Marshaller_AddSampleCommentsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleCommentsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleRatingsRequest> __Marshaller_AddSampleRatingsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleRatingsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleRatingsResponse> __Marshaller_AddSampleRatingsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleRatingsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleUsersRequest> __Marshaller_AddSampleUsersRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleUsersRequest.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleUsersResponse> __Marshaller_AddSampleUsersResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleUsersResponse.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleVideoViewsRequest> __Marshaller_AddSampleVideoViewsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleVideoViewsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleVideoViewsResponse> __Marshaller_AddSampleVideoViewsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleVideoViewsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest> __Marshaller_AddSampleYouTubeVideosRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse> __Marshaller_AddSampleYouTubeVideosResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest> __Marshaller_RefreshYouTubeSourcesRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse> __Marshaller_RefreshYouTubeSourcesResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse.Parser.ParseFrom);

    static readonly Method<global::KillrVideo.SampleData.AddSampleCommentsRequest, global::KillrVideo.SampleData.AddSampleCommentsResponse> __Method_AddSampleComments = new Method<global::KillrVideo.SampleData.AddSampleCommentsRequest, global::KillrVideo.SampleData.AddSampleCommentsResponse>(
        MethodType.Unary,
        __ServiceName,
        "AddSampleComments",
        __Marshaller_AddSampleCommentsRequest,
        __Marshaller_AddSampleCommentsResponse);

    static readonly Method<global::KillrVideo.SampleData.AddSampleRatingsRequest, global::KillrVideo.SampleData.AddSampleRatingsResponse> __Method_AddSampleRatings = new Method<global::KillrVideo.SampleData.AddSampleRatingsRequest, global::KillrVideo.SampleData.AddSampleRatingsResponse>(
        MethodType.Unary,
        __ServiceName,
        "AddSampleRatings",
        __Marshaller_AddSampleRatingsRequest,
        __Marshaller_AddSampleRatingsResponse);

    static readonly Method<global::KillrVideo.SampleData.AddSampleUsersRequest, global::KillrVideo.SampleData.AddSampleUsersResponse> __Method_AddSampleUsers = new Method<global::KillrVideo.SampleData.AddSampleUsersRequest, global::KillrVideo.SampleData.AddSampleUsersResponse>(
        MethodType.Unary,
        __ServiceName,
        "AddSampleUsers",
        __Marshaller_AddSampleUsersRequest,
        __Marshaller_AddSampleUsersResponse);

    static readonly Method<global::KillrVideo.SampleData.AddSampleVideoViewsRequest, global::KillrVideo.SampleData.AddSampleVideoViewsResponse> __Method_AddSampleVideoViews = new Method<global::KillrVideo.SampleData.AddSampleVideoViewsRequest, global::KillrVideo.SampleData.AddSampleVideoViewsResponse>(
        MethodType.Unary,
        __ServiceName,
        "AddSampleVideoViews",
        __Marshaller_AddSampleVideoViewsRequest,
        __Marshaller_AddSampleVideoViewsResponse);

    static readonly Method<global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest, global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse> __Method_AddSampleYouTubeVideos = new Method<global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest, global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse>(
        MethodType.Unary,
        __ServiceName,
        "AddSampleYouTubeVideos",
        __Marshaller_AddSampleYouTubeVideosRequest,
        __Marshaller_AddSampleYouTubeVideosResponse);

    static readonly Method<global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest, global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse> __Method_RefreshYouTubeSources = new Method<global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest, global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse>(
        MethodType.Unary,
        __ServiceName,
        "RefreshYouTubeSources",
        __Marshaller_RefreshYouTubeSourcesRequest,
        __Marshaller_RefreshYouTubeSourcesResponse);

    // service descriptor
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::KillrVideo.SampleData.SampleDataServiceReflection.Descriptor.Services[0]; }
    }

    // client interface
    public interface ISampleDataServiceClient
    {
      global::KillrVideo.SampleData.AddSampleCommentsResponse AddSampleComments(global::KillrVideo.SampleData.AddSampleCommentsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::KillrVideo.SampleData.AddSampleCommentsResponse AddSampleComments(global::KillrVideo.SampleData.AddSampleCommentsRequest request, CallOptions options);
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleCommentsResponse> AddSampleCommentsAsync(global::KillrVideo.SampleData.AddSampleCommentsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleCommentsResponse> AddSampleCommentsAsync(global::KillrVideo.SampleData.AddSampleCommentsRequest request, CallOptions options);
      global::KillrVideo.SampleData.AddSampleRatingsResponse AddSampleRatings(global::KillrVideo.SampleData.AddSampleRatingsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::KillrVideo.SampleData.AddSampleRatingsResponse AddSampleRatings(global::KillrVideo.SampleData.AddSampleRatingsRequest request, CallOptions options);
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleRatingsResponse> AddSampleRatingsAsync(global::KillrVideo.SampleData.AddSampleRatingsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleRatingsResponse> AddSampleRatingsAsync(global::KillrVideo.SampleData.AddSampleRatingsRequest request, CallOptions options);
      global::KillrVideo.SampleData.AddSampleUsersResponse AddSampleUsers(global::KillrVideo.SampleData.AddSampleUsersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::KillrVideo.SampleData.AddSampleUsersResponse AddSampleUsers(global::KillrVideo.SampleData.AddSampleUsersRequest request, CallOptions options);
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleUsersResponse> AddSampleUsersAsync(global::KillrVideo.SampleData.AddSampleUsersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleUsersResponse> AddSampleUsersAsync(global::KillrVideo.SampleData.AddSampleUsersRequest request, CallOptions options);
      global::KillrVideo.SampleData.AddSampleVideoViewsResponse AddSampleVideoViews(global::KillrVideo.SampleData.AddSampleVideoViewsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::KillrVideo.SampleData.AddSampleVideoViewsResponse AddSampleVideoViews(global::KillrVideo.SampleData.AddSampleVideoViewsRequest request, CallOptions options);
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleVideoViewsResponse> AddSampleVideoViewsAsync(global::KillrVideo.SampleData.AddSampleVideoViewsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleVideoViewsResponse> AddSampleVideoViewsAsync(global::KillrVideo.SampleData.AddSampleVideoViewsRequest request, CallOptions options);
      global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse AddSampleYouTubeVideos(global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse AddSampleYouTubeVideos(global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest request, CallOptions options);
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse> AddSampleYouTubeVideosAsync(global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse> AddSampleYouTubeVideosAsync(global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest request, CallOptions options);
      global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse RefreshYouTubeSources(global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse RefreshYouTubeSources(global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest request, CallOptions options);
      AsyncUnaryCall<global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse> RefreshYouTubeSourcesAsync(global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse> RefreshYouTubeSourcesAsync(global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest request, CallOptions options);
    }

    // server-side interface
    public interface ISampleDataService
    {
      Task<global::KillrVideo.SampleData.AddSampleCommentsResponse> AddSampleComments(global::KillrVideo.SampleData.AddSampleCommentsRequest request, ServerCallContext context);
      Task<global::KillrVideo.SampleData.AddSampleRatingsResponse> AddSampleRatings(global::KillrVideo.SampleData.AddSampleRatingsRequest request, ServerCallContext context);
      Task<global::KillrVideo.SampleData.AddSampleUsersResponse> AddSampleUsers(global::KillrVideo.SampleData.AddSampleUsersRequest request, ServerCallContext context);
      Task<global::KillrVideo.SampleData.AddSampleVideoViewsResponse> AddSampleVideoViews(global::KillrVideo.SampleData.AddSampleVideoViewsRequest request, ServerCallContext context);
      Task<global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse> AddSampleYouTubeVideos(global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest request, ServerCallContext context);
      Task<global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse> RefreshYouTubeSources(global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest request, ServerCallContext context);
    }

    // client stub
    public class SampleDataServiceClient : ClientBase, ISampleDataServiceClient
    {
      public SampleDataServiceClient(Channel channel) : base(channel)
      {
      }
      public global::KillrVideo.SampleData.AddSampleCommentsResponse AddSampleComments(global::KillrVideo.SampleData.AddSampleCommentsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleComments, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.AddSampleCommentsResponse AddSampleComments(global::KillrVideo.SampleData.AddSampleCommentsRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleComments, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleCommentsResponse> AddSampleCommentsAsync(global::KillrVideo.SampleData.AddSampleCommentsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleComments, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleCommentsResponse> AddSampleCommentsAsync(global::KillrVideo.SampleData.AddSampleCommentsRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleComments, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.AddSampleRatingsResponse AddSampleRatings(global::KillrVideo.SampleData.AddSampleRatingsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleRatings, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.AddSampleRatingsResponse AddSampleRatings(global::KillrVideo.SampleData.AddSampleRatingsRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleRatings, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleRatingsResponse> AddSampleRatingsAsync(global::KillrVideo.SampleData.AddSampleRatingsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleRatings, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleRatingsResponse> AddSampleRatingsAsync(global::KillrVideo.SampleData.AddSampleRatingsRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleRatings, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.AddSampleUsersResponse AddSampleUsers(global::KillrVideo.SampleData.AddSampleUsersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleUsers, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.AddSampleUsersResponse AddSampleUsers(global::KillrVideo.SampleData.AddSampleUsersRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleUsers, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleUsersResponse> AddSampleUsersAsync(global::KillrVideo.SampleData.AddSampleUsersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleUsers, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleUsersResponse> AddSampleUsersAsync(global::KillrVideo.SampleData.AddSampleUsersRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleUsers, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.AddSampleVideoViewsResponse AddSampleVideoViews(global::KillrVideo.SampleData.AddSampleVideoViewsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleVideoViews, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.AddSampleVideoViewsResponse AddSampleVideoViews(global::KillrVideo.SampleData.AddSampleVideoViewsRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleVideoViews, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleVideoViewsResponse> AddSampleVideoViewsAsync(global::KillrVideo.SampleData.AddSampleVideoViewsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleVideoViews, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleVideoViewsResponse> AddSampleVideoViewsAsync(global::KillrVideo.SampleData.AddSampleVideoViewsRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleVideoViews, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse AddSampleYouTubeVideos(global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleYouTubeVideos, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse AddSampleYouTubeVideos(global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleYouTubeVideos, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse> AddSampleYouTubeVideosAsync(global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_AddSampleYouTubeVideos, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.AddSampleYouTubeVideosResponse> AddSampleYouTubeVideosAsync(global::KillrVideo.SampleData.AddSampleYouTubeVideosRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_AddSampleYouTubeVideos, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse RefreshYouTubeSources(global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_RefreshYouTubeSources, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse RefreshYouTubeSources(global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_RefreshYouTubeSources, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse> RefreshYouTubeSourcesAsync(global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_RefreshYouTubeSources, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::KillrVideo.SampleData.RefreshYouTubeSourcesResponse> RefreshYouTubeSourcesAsync(global::KillrVideo.SampleData.RefreshYouTubeSourcesRequest request, CallOptions options)
      {
        var call = CreateCall(__Method_RefreshYouTubeSources, options);
        return Calls.AsyncUnaryCall(call, request);
      }
    }

    // creates service definition that can be registered with a server
    public static ServerServiceDefinition BindService(ISampleDataService serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder(__ServiceName)
          .AddMethod(__Method_AddSampleComments, serviceImpl.AddSampleComments)
          .AddMethod(__Method_AddSampleRatings, serviceImpl.AddSampleRatings)
          .AddMethod(__Method_AddSampleUsers, serviceImpl.AddSampleUsers)
          .AddMethod(__Method_AddSampleVideoViews, serviceImpl.AddSampleVideoViews)
          .AddMethod(__Method_AddSampleYouTubeVideos, serviceImpl.AddSampleYouTubeVideos)
          .AddMethod(__Method_RefreshYouTubeSources, serviceImpl.RefreshYouTubeSources).Build();
    }

    // creates a new client
    public static SampleDataServiceClient NewClient(Channel channel)
    {
      return new SampleDataServiceClient(channel);
    }

  }
}
#endregion
