// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: suggested-videos/suggested_videos_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace KillrVideo.SuggestedVideos {

  /// <summary>Holder for reflection information generated from suggested-videos/suggested_videos_service.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class SuggestedVideosServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for suggested-videos/suggested_videos_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SuggestedVideosServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9zdWdnZXN0ZWQtdmlkZW9zL3N1Z2dlc3RlZF92aWRlb3Nfc2VydmljZS5w",
            "cm90bxIba2lsbHJ2aWRlby5zdWdnZXN0ZWRfdmlkZW9zGh9nb29nbGUvcHJv",
            "dG9idWYvdGltZXN0YW1wLnByb3RvGhljb21tb24vY29tbW9uX3R5cGVzLnBy",
            "b3RvIm0KF0dldFJlbGF0ZWRWaWRlb3NSZXF1ZXN0EikKCHZpZGVvX2lkGAEg",
            "ASgLMhcua2lsbHJ2aWRlby5jb21tb24uVXVpZBIRCglwYWdlX3NpemUYAiAB",
            "KAUSFAoMcGFnaW5nX3N0YXRlGBAgASgJIp8BChhHZXRSZWxhdGVkVmlkZW9z",
            "UmVzcG9uc2USKQoIdmlkZW9faWQYASABKAsyFy5raWxscnZpZGVvLmNvbW1v",
            "bi5VdWlkEkIKBnZpZGVvcxgCIAMoCzIyLmtpbGxydmlkZW8uc3VnZ2VzdGVk",
            "X3ZpZGVvcy5TdWdnZXN0ZWRWaWRlb1ByZXZpZXcSFAoMcGFnaW5nX3N0YXRl",
            "GAMgASgJIm8KGkdldFN1Z2dlc3RlZEZvclVzZXJSZXF1ZXN0EigKB3VzZXJf",
            "aWQYASABKAsyFy5raWxscnZpZGVvLmNvbW1vbi5VdWlkEhEKCXBhZ2Vfc2l6",
            "ZRgCIAEoBRIUCgxwYWdpbmdfc3RhdGUYECABKAkioQEKG0dldFN1Z2dlc3Rl",
            "ZEZvclVzZXJSZXNwb25zZRIoCgd1c2VyX2lkGAEgASgLMhcua2lsbHJ2aWRl",
            "by5jb21tb24uVXVpZBJCCgZ2aWRlb3MYAiADKAsyMi5raWxscnZpZGVvLnN1",
            "Z2dlc3RlZF92aWRlb3MuU3VnZ2VzdGVkVmlkZW9QcmV2aWV3EhQKDHBhZ2lu",
            "Z19zdGF0ZRgDIAEoCSLKAQoVU3VnZ2VzdGVkVmlkZW9QcmV2aWV3EikKCHZp",
            "ZGVvX2lkGAEgASgLMhcua2lsbHJ2aWRlby5jb21tb24uVXVpZBIuCgphZGRl",
            "ZF9kYXRlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIMCgRu",
            "YW1lGAMgASgJEh4KFnByZXZpZXdfaW1hZ2VfbG9jYXRpb24YBCABKAkSKAoH",
            "dXNlcl9pZBgFIAEoCzIXLmtpbGxydmlkZW8uY29tbW9uLlV1aWQyowIKFVN1",
            "Z2dlc3RlZFZpZGVvU2VydmljZRJ/ChBHZXRSZWxhdGVkVmlkZW9zEjQua2ls",
            "bHJ2aWRlby5zdWdnZXN0ZWRfdmlkZW9zLkdldFJlbGF0ZWRWaWRlb3NSZXF1",
            "ZXN0GjUua2lsbHJ2aWRlby5zdWdnZXN0ZWRfdmlkZW9zLkdldFJlbGF0ZWRW",
            "aWRlb3NSZXNwb25zZRKIAQoTR2V0U3VnZ2VzdGVkRm9yVXNlchI3LmtpbGxy",
            "dmlkZW8uc3VnZ2VzdGVkX3ZpZGVvcy5HZXRTdWdnZXN0ZWRGb3JVc2VyUmVx",
            "dWVzdBo4LmtpbGxydmlkZW8uc3VnZ2VzdGVkX3ZpZGVvcy5HZXRTdWdnZXN0",
            "ZWRGb3JVc2VyUmVzcG9uc2VCHaoCGktpbGxyVmlkZW8uU3VnZ2VzdGVkVmlk",
            "ZW9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::KillrVideo.Protobuf.CommonTypesReflection.Descriptor, },
          new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest), global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest.Parser, new[]{ "VideoId", "PageSize", "PagingState" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse), global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse.Parser, new[]{ "VideoId", "Videos", "PagingState" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest), global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest.Parser, new[]{ "UserId", "PageSize", "PagingState" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse), global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse.Parser, new[]{ "UserId", "Videos", "PagingState" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.SuggestedVideos.SuggestedVideoPreview), global::KillrVideo.SuggestedVideos.SuggestedVideoPreview.Parser, new[]{ "VideoId", "AddedDate", "Name", "PreviewImageLocation", "UserId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  Request to get videos related to another video
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GetRelatedVideosRequest : pb::IMessage<GetRelatedVideosRequest> {
    private static readonly pb::MessageParser<GetRelatedVideosRequest> _parser = new pb::MessageParser<GetRelatedVideosRequest>(() => new GetRelatedVideosRequest());
    public static pb::MessageParser<GetRelatedVideosRequest> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.SuggestedVideos.SuggestedVideosServiceReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GetRelatedVideosRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GetRelatedVideosRequest(GetRelatedVideosRequest other) : this() {
      VideoId = other.videoId_ != null ? other.VideoId.Clone() : null;
      pageSize_ = other.pageSize_;
      pagingState_ = other.pagingState_;
    }

    public GetRelatedVideosRequest Clone() {
      return new GetRelatedVideosRequest(this);
    }

    /// <summary>Field number for the "video_id" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private global::KillrVideo.Protobuf.Uuid videoId_;
    public global::KillrVideo.Protobuf.Uuid VideoId {
      get { return videoId_; }
      set {
        videoId_ = value;
      }
    }

    /// <summary>Field number for the "page_size" field.</summary>
    public const int PageSizeFieldNumber = 2;
    private int pageSize_;
    public int PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    /// <summary>Field number for the "paging_state" field.</summary>
    public const int PagingStateFieldNumber = 16;
    private string pagingState_ = "";
    public string PagingState {
      get { return pagingState_; }
      set {
        pagingState_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GetRelatedVideosRequest);
    }

    public bool Equals(GetRelatedVideosRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VideoId, other.VideoId)) return false;
      if (PageSize != other.PageSize) return false;
      if (PagingState != other.PagingState) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (videoId_ != null) hash ^= VideoId.GetHashCode();
      if (PageSize != 0) hash ^= PageSize.GetHashCode();
      if (PagingState.Length != 0) hash ^= PagingState.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (videoId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VideoId);
      }
      if (PageSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PageSize);
      }
      if (PagingState.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(PagingState);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (videoId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VideoId);
      }
      if (PageSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageSize);
      }
      if (PagingState.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PagingState);
      }
      return size;
    }

    public void MergeFrom(GetRelatedVideosRequest other) {
      if (other == null) {
        return;
      }
      if (other.videoId_ != null) {
        if (videoId_ == null) {
          videoId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        VideoId.MergeFrom(other.VideoId);
      }
      if (other.PageSize != 0) {
        PageSize = other.PageSize;
      }
      if (other.PagingState.Length != 0) {
        PagingState = other.PagingState;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (videoId_ == null) {
              videoId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(videoId_);
            break;
          }
          case 16: {
            PageSize = input.ReadInt32();
            break;
          }
          case 130: {
            PagingState = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Response when getting messages related to another video
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GetRelatedVideosResponse : pb::IMessage<GetRelatedVideosResponse> {
    private static readonly pb::MessageParser<GetRelatedVideosResponse> _parser = new pb::MessageParser<GetRelatedVideosResponse>(() => new GetRelatedVideosResponse());
    public static pb::MessageParser<GetRelatedVideosResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.SuggestedVideos.SuggestedVideosServiceReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GetRelatedVideosResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GetRelatedVideosResponse(GetRelatedVideosResponse other) : this() {
      VideoId = other.videoId_ != null ? other.VideoId.Clone() : null;
      videos_ = other.videos_.Clone();
      pagingState_ = other.pagingState_;
    }

    public GetRelatedVideosResponse Clone() {
      return new GetRelatedVideosResponse(this);
    }

    /// <summary>Field number for the "video_id" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private global::KillrVideo.Protobuf.Uuid videoId_;
    public global::KillrVideo.Protobuf.Uuid VideoId {
      get { return videoId_; }
      set {
        videoId_ = value;
      }
    }

    /// <summary>Field number for the "videos" field.</summary>
    public const int VideosFieldNumber = 2;
    private static readonly pb::FieldCodec<global::KillrVideo.SuggestedVideos.SuggestedVideoPreview> _repeated_videos_codec
        = pb::FieldCodec.ForMessage(18, global::KillrVideo.SuggestedVideos.SuggestedVideoPreview.Parser);
    private readonly pbc::RepeatedField<global::KillrVideo.SuggestedVideos.SuggestedVideoPreview> videos_ = new pbc::RepeatedField<global::KillrVideo.SuggestedVideos.SuggestedVideoPreview>();
    public pbc::RepeatedField<global::KillrVideo.SuggestedVideos.SuggestedVideoPreview> Videos {
      get { return videos_; }
    }

    /// <summary>Field number for the "paging_state" field.</summary>
    public const int PagingStateFieldNumber = 3;
    private string pagingState_ = "";
    public string PagingState {
      get { return pagingState_; }
      set {
        pagingState_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GetRelatedVideosResponse);
    }

    public bool Equals(GetRelatedVideosResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VideoId, other.VideoId)) return false;
      if(!videos_.Equals(other.videos_)) return false;
      if (PagingState != other.PagingState) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (videoId_ != null) hash ^= VideoId.GetHashCode();
      hash ^= videos_.GetHashCode();
      if (PagingState.Length != 0) hash ^= PagingState.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (videoId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VideoId);
      }
      videos_.WriteTo(output, _repeated_videos_codec);
      if (PagingState.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PagingState);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (videoId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VideoId);
      }
      size += videos_.CalculateSize(_repeated_videos_codec);
      if (PagingState.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PagingState);
      }
      return size;
    }

    public void MergeFrom(GetRelatedVideosResponse other) {
      if (other == null) {
        return;
      }
      if (other.videoId_ != null) {
        if (videoId_ == null) {
          videoId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        VideoId.MergeFrom(other.VideoId);
      }
      videos_.Add(other.videos_);
      if (other.PagingState.Length != 0) {
        PagingState = other.PagingState;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (videoId_ == null) {
              videoId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(videoId_);
            break;
          }
          case 18: {
            videos_.AddEntriesFrom(input, _repeated_videos_codec);
            break;
          }
          case 26: {
            PagingState = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Request to get personalized video suggestions for a user
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GetSuggestedForUserRequest : pb::IMessage<GetSuggestedForUserRequest> {
    private static readonly pb::MessageParser<GetSuggestedForUserRequest> _parser = new pb::MessageParser<GetSuggestedForUserRequest>(() => new GetSuggestedForUserRequest());
    public static pb::MessageParser<GetSuggestedForUserRequest> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.SuggestedVideos.SuggestedVideosServiceReflection.Descriptor.MessageTypes[2]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GetSuggestedForUserRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GetSuggestedForUserRequest(GetSuggestedForUserRequest other) : this() {
      UserId = other.userId_ != null ? other.UserId.Clone() : null;
      pageSize_ = other.pageSize_;
      pagingState_ = other.pagingState_;
    }

    public GetSuggestedForUserRequest Clone() {
      return new GetSuggestedForUserRequest(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private global::KillrVideo.Protobuf.Uuid userId_;
    public global::KillrVideo.Protobuf.Uuid UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "page_size" field.</summary>
    public const int PageSizeFieldNumber = 2;
    private int pageSize_;
    public int PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    /// <summary>Field number for the "paging_state" field.</summary>
    public const int PagingStateFieldNumber = 16;
    private string pagingState_ = "";
    public string PagingState {
      get { return pagingState_; }
      set {
        pagingState_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GetSuggestedForUserRequest);
    }

    public bool Equals(GetSuggestedForUserRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UserId, other.UserId)) return false;
      if (PageSize != other.PageSize) return false;
      if (PagingState != other.PagingState) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (userId_ != null) hash ^= UserId.GetHashCode();
      if (PageSize != 0) hash ^= PageSize.GetHashCode();
      if (PagingState.Length != 0) hash ^= PagingState.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (userId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserId);
      }
      if (PageSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PageSize);
      }
      if (PagingState.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(PagingState);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (userId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserId);
      }
      if (PageSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageSize);
      }
      if (PagingState.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PagingState);
      }
      return size;
    }

    public void MergeFrom(GetSuggestedForUserRequest other) {
      if (other == null) {
        return;
      }
      if (other.userId_ != null) {
        if (userId_ == null) {
          userId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        UserId.MergeFrom(other.UserId);
      }
      if (other.PageSize != 0) {
        PageSize = other.PageSize;
      }
      if (other.PagingState.Length != 0) {
        PagingState = other.PagingState;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (userId_ == null) {
              userId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(userId_);
            break;
          }
          case 16: {
            PageSize = input.ReadInt32();
            break;
          }
          case 130: {
            PagingState = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Response when getting personalized suggestions for a user
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GetSuggestedForUserResponse : pb::IMessage<GetSuggestedForUserResponse> {
    private static readonly pb::MessageParser<GetSuggestedForUserResponse> _parser = new pb::MessageParser<GetSuggestedForUserResponse>(() => new GetSuggestedForUserResponse());
    public static pb::MessageParser<GetSuggestedForUserResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.SuggestedVideos.SuggestedVideosServiceReflection.Descriptor.MessageTypes[3]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GetSuggestedForUserResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GetSuggestedForUserResponse(GetSuggestedForUserResponse other) : this() {
      UserId = other.userId_ != null ? other.UserId.Clone() : null;
      videos_ = other.videos_.Clone();
      pagingState_ = other.pagingState_;
    }

    public GetSuggestedForUserResponse Clone() {
      return new GetSuggestedForUserResponse(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private global::KillrVideo.Protobuf.Uuid userId_;
    public global::KillrVideo.Protobuf.Uuid UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "videos" field.</summary>
    public const int VideosFieldNumber = 2;
    private static readonly pb::FieldCodec<global::KillrVideo.SuggestedVideos.SuggestedVideoPreview> _repeated_videos_codec
        = pb::FieldCodec.ForMessage(18, global::KillrVideo.SuggestedVideos.SuggestedVideoPreview.Parser);
    private readonly pbc::RepeatedField<global::KillrVideo.SuggestedVideos.SuggestedVideoPreview> videos_ = new pbc::RepeatedField<global::KillrVideo.SuggestedVideos.SuggestedVideoPreview>();
    public pbc::RepeatedField<global::KillrVideo.SuggestedVideos.SuggestedVideoPreview> Videos {
      get { return videos_; }
    }

    /// <summary>Field number for the "paging_state" field.</summary>
    public const int PagingStateFieldNumber = 3;
    private string pagingState_ = "";
    public string PagingState {
      get { return pagingState_; }
      set {
        pagingState_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GetSuggestedForUserResponse);
    }

    public bool Equals(GetSuggestedForUserResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UserId, other.UserId)) return false;
      if(!videos_.Equals(other.videos_)) return false;
      if (PagingState != other.PagingState) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (userId_ != null) hash ^= UserId.GetHashCode();
      hash ^= videos_.GetHashCode();
      if (PagingState.Length != 0) hash ^= PagingState.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (userId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserId);
      }
      videos_.WriteTo(output, _repeated_videos_codec);
      if (PagingState.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PagingState);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (userId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserId);
      }
      size += videos_.CalculateSize(_repeated_videos_codec);
      if (PagingState.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PagingState);
      }
      return size;
    }

    public void MergeFrom(GetSuggestedForUserResponse other) {
      if (other == null) {
        return;
      }
      if (other.userId_ != null) {
        if (userId_ == null) {
          userId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        UserId.MergeFrom(other.UserId);
      }
      videos_.Add(other.videos_);
      if (other.PagingState.Length != 0) {
        PagingState = other.PagingState;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (userId_ == null) {
              userId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(userId_);
            break;
          }
          case 18: {
            videos_.AddEntriesFrom(input, _repeated_videos_codec);
            break;
          }
          case 26: {
            PagingState = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Video preview data for a video returned as a video suggestion
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class SuggestedVideoPreview : pb::IMessage<SuggestedVideoPreview> {
    private static readonly pb::MessageParser<SuggestedVideoPreview> _parser = new pb::MessageParser<SuggestedVideoPreview>(() => new SuggestedVideoPreview());
    public static pb::MessageParser<SuggestedVideoPreview> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.SuggestedVideos.SuggestedVideosServiceReflection.Descriptor.MessageTypes[4]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public SuggestedVideoPreview() {
      OnConstruction();
    }

    partial void OnConstruction();

    public SuggestedVideoPreview(SuggestedVideoPreview other) : this() {
      VideoId = other.videoId_ != null ? other.VideoId.Clone() : null;
      AddedDate = other.addedDate_ != null ? other.AddedDate.Clone() : null;
      name_ = other.name_;
      previewImageLocation_ = other.previewImageLocation_;
      UserId = other.userId_ != null ? other.UserId.Clone() : null;
    }

    public SuggestedVideoPreview Clone() {
      return new SuggestedVideoPreview(this);
    }

    /// <summary>Field number for the "video_id" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private global::KillrVideo.Protobuf.Uuid videoId_;
    public global::KillrVideo.Protobuf.Uuid VideoId {
      get { return videoId_; }
      set {
        videoId_ = value;
      }
    }

    /// <summary>Field number for the "added_date" field.</summary>
    public const int AddedDateFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp addedDate_;
    public global::Google.Protobuf.WellKnownTypes.Timestamp AddedDate {
      get { return addedDate_; }
      set {
        addedDate_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    public string Name {
      get { return name_; }
      set {
        name_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "preview_image_location" field.</summary>
    public const int PreviewImageLocationFieldNumber = 4;
    private string previewImageLocation_ = "";
    public string PreviewImageLocation {
      get { return previewImageLocation_; }
      set {
        previewImageLocation_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 5;
    private global::KillrVideo.Protobuf.Uuid userId_;
    public global::KillrVideo.Protobuf.Uuid UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as SuggestedVideoPreview);
    }

    public bool Equals(SuggestedVideoPreview other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VideoId, other.VideoId)) return false;
      if (!object.Equals(AddedDate, other.AddedDate)) return false;
      if (Name != other.Name) return false;
      if (PreviewImageLocation != other.PreviewImageLocation) return false;
      if (!object.Equals(UserId, other.UserId)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (videoId_ != null) hash ^= VideoId.GetHashCode();
      if (addedDate_ != null) hash ^= AddedDate.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (PreviewImageLocation.Length != 0) hash ^= PreviewImageLocation.GetHashCode();
      if (userId_ != null) hash ^= UserId.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (videoId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VideoId);
      }
      if (addedDate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AddedDate);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (PreviewImageLocation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PreviewImageLocation);
      }
      if (userId_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(UserId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (videoId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VideoId);
      }
      if (addedDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AddedDate);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (PreviewImageLocation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PreviewImageLocation);
      }
      if (userId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserId);
      }
      return size;
    }

    public void MergeFrom(SuggestedVideoPreview other) {
      if (other == null) {
        return;
      }
      if (other.videoId_ != null) {
        if (videoId_ == null) {
          videoId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        VideoId.MergeFrom(other.VideoId);
      }
      if (other.addedDate_ != null) {
        if (addedDate_ == null) {
          addedDate_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        AddedDate.MergeFrom(other.AddedDate);
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.PreviewImageLocation.Length != 0) {
        PreviewImageLocation = other.PreviewImageLocation;
      }
      if (other.userId_ != null) {
        if (userId_ == null) {
          userId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        UserId.MergeFrom(other.UserId);
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (videoId_ == null) {
              videoId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(videoId_);
            break;
          }
          case 18: {
            if (addedDate_ == null) {
              addedDate_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(addedDate_);
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            PreviewImageLocation = input.ReadString();
            break;
          }
          case 42: {
            if (userId_ == null) {
              userId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(userId_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
