// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: suggested-videos/suggested_videos_service.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace KillrVideo.SuggestedVideos {
  /// <summary>
  ///  Service responsible for generating video suggestions
  /// </summary>
  public static class SuggestedVideoService
  {
    static readonly string __ServiceName = "killrvideo.suggested_videos.SuggestedVideoService";

    static readonly Marshaller<global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest> __Marshaller_GetRelatedVideosRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse> __Marshaller_GetRelatedVideosResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest> __Marshaller_GetSuggestedForUserRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest.Parser.ParseFrom);
    static readonly Marshaller<global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse> __Marshaller_GetSuggestedForUserResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse.Parser.ParseFrom);

    static readonly Method<global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest, global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse> __Method_GetRelatedVideos = new Method<global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest, global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse>(
        MethodType.Unary,
        __ServiceName,
        "GetRelatedVideos",
        __Marshaller_GetRelatedVideosRequest,
        __Marshaller_GetRelatedVideosResponse);

    static readonly Method<global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest, global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse> __Method_GetSuggestedForUser = new Method<global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest, global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse>(
        MethodType.Unary,
        __ServiceName,
        "GetSuggestedForUser",
        __Marshaller_GetSuggestedForUserRequest,
        __Marshaller_GetSuggestedForUserResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::KillrVideo.SuggestedVideos.SuggestedVideosServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SuggestedVideoService</summary>
    public abstract class SuggestedVideoServiceBase
    {
      /// <summary>
      ///  Gets videos related to another video
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse> GetRelatedVideos(global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Gets personalized video suggestions for a user
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse> GetSuggestedForUser(global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SuggestedVideoService</summary>
    public class SuggestedVideoServiceClient : ClientBase<SuggestedVideoServiceClient>
    {
      /// <summary>Creates a new client for SuggestedVideoService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SuggestedVideoServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SuggestedVideoService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SuggestedVideoServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SuggestedVideoServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SuggestedVideoServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Gets videos related to another video
      /// </summary>
      public virtual global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse GetRelatedVideos(global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRelatedVideos(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets videos related to another video
      /// </summary>
      public virtual global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse GetRelatedVideos(global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRelatedVideos, null, options, request);
      }
      /// <summary>
      ///  Gets videos related to another video
      /// </summary>
      public virtual AsyncUnaryCall<global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse> GetRelatedVideosAsync(global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRelatedVideosAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets videos related to another video
      /// </summary>
      public virtual AsyncUnaryCall<global::KillrVideo.SuggestedVideos.GetRelatedVideosResponse> GetRelatedVideosAsync(global::KillrVideo.SuggestedVideos.GetRelatedVideosRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRelatedVideos, null, options, request);
      }
      /// <summary>
      ///  Gets personalized video suggestions for a user
      /// </summary>
      public virtual global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse GetSuggestedForUser(global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetSuggestedForUser(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets personalized video suggestions for a user
      /// </summary>
      public virtual global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse GetSuggestedForUser(global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSuggestedForUser, null, options, request);
      }
      /// <summary>
      ///  Gets personalized video suggestions for a user
      /// </summary>
      public virtual AsyncUnaryCall<global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse> GetSuggestedForUserAsync(global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetSuggestedForUserAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets personalized video suggestions for a user
      /// </summary>
      public virtual AsyncUnaryCall<global::KillrVideo.SuggestedVideos.GetSuggestedForUserResponse> GetSuggestedForUserAsync(global::KillrVideo.SuggestedVideos.GetSuggestedForUserRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSuggestedForUser, null, options, request);
      }
      protected override SuggestedVideoServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SuggestedVideoServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(SuggestedVideoServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetRelatedVideos, serviceImpl.GetRelatedVideos)
          .AddMethod(__Method_GetSuggestedForUser, serviceImpl.GetSuggestedForUser).Build();
    }

  }
}
#endregion
