// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics/statistics_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace KillrVideo.Statistics {

  /// <summary>Holder for reflection information generated from statistics/statistics_service.proto</summary>
  public static partial class StatisticsServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for statistics/statistics_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StatisticsServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNzdGF0aXN0aWNzL3N0YXRpc3RpY3Nfc2VydmljZS5wcm90bxIVa2lsbHJ2",
            "aWRlby5zdGF0aXN0aWNzGhljb21tb24vY29tbW9uX3R5cGVzLnByb3RvIkkK",
            "HFJlY29yZFBsYXliYWNrU3RhcnRlZFJlcXVlc3QSKQoIdmlkZW9faWQYASAB",
            "KAsyFy5raWxscnZpZGVvLmNvbW1vbi5VdWlkIh8KHVJlY29yZFBsYXliYWNr",
            "U3RhcnRlZFJlc3BvbnNlIkUKF0dldE51bWJlck9mUGxheXNSZXF1ZXN0EioK",
            "CXZpZGVvX2lkcxgBIAMoCzIXLmtpbGxydmlkZW8uY29tbW9uLlV1aWQiSwoY",
            "R2V0TnVtYmVyT2ZQbGF5c1Jlc3BvbnNlEi8KBXN0YXRzGAEgAygLMiAua2ls",
            "bHJ2aWRlby5zdGF0aXN0aWNzLlBsYXlTdGF0cyJFCglQbGF5U3RhdHMSKQoI",
            "dmlkZW9faWQYASABKAsyFy5raWxscnZpZGVvLmNvbW1vbi5VdWlkEg0KBXZp",
            "ZXdzGAIgASgDMo0CChFTdGF0aXN0aWNzU2VydmljZRKCAQoVUmVjb3JkUGxh",
            "eWJhY2tTdGFydGVkEjMua2lsbHJ2aWRlby5zdGF0aXN0aWNzLlJlY29yZFBs",
            "YXliYWNrU3RhcnRlZFJlcXVlc3QaNC5raWxscnZpZGVvLnN0YXRpc3RpY3Mu",
            "UmVjb3JkUGxheWJhY2tTdGFydGVkUmVzcG9uc2UScwoQR2V0TnVtYmVyT2ZQ",
            "bGF5cxIuLmtpbGxydmlkZW8uc3RhdGlzdGljcy5HZXROdW1iZXJPZlBsYXlz",
            "UmVxdWVzdBovLmtpbGxydmlkZW8uc3RhdGlzdGljcy5HZXROdW1iZXJPZlBs",
            "YXlzUmVzcG9uc2VCGKoCFUtpbGxyVmlkZW8uU3RhdGlzdGljc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::KillrVideo.Protobuf.CommonTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::KillrVideo.Statistics.RecordPlaybackStartedRequest), global::KillrVideo.Statistics.RecordPlaybackStartedRequest.Parser, new[]{ "VideoId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::KillrVideo.Statistics.RecordPlaybackStartedResponse), global::KillrVideo.Statistics.RecordPlaybackStartedResponse.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::KillrVideo.Statistics.GetNumberOfPlaysRequest), global::KillrVideo.Statistics.GetNumberOfPlaysRequest.Parser, new[]{ "VideoIds" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::KillrVideo.Statistics.GetNumberOfPlaysResponse), global::KillrVideo.Statistics.GetNumberOfPlaysResponse.Parser, new[]{ "Stats" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::KillrVideo.Statistics.PlayStats), global::KillrVideo.Statistics.PlayStats.Parser, new[]{ "VideoId", "Views" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  Request for recording that a user started playing back a video
  /// </summary>
  public sealed partial class RecordPlaybackStartedRequest : pb::IMessage<RecordPlaybackStartedRequest> {
    private static readonly pb::MessageParser<RecordPlaybackStartedRequest> _parser = new pb::MessageParser<RecordPlaybackStartedRequest>(() => new RecordPlaybackStartedRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RecordPlaybackStartedRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Statistics.StatisticsServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecordPlaybackStartedRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecordPlaybackStartedRequest(RecordPlaybackStartedRequest other) : this() {
      VideoId = other.videoId_ != null ? other.VideoId.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecordPlaybackStartedRequest Clone() {
      return new RecordPlaybackStartedRequest(this);
    }

    /// <summary>Field number for the "video_id" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private global::KillrVideo.Protobuf.Uuid videoId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::KillrVideo.Protobuf.Uuid VideoId {
      get { return videoId_; }
      set {
        videoId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RecordPlaybackStartedRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RecordPlaybackStartedRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VideoId, other.VideoId)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (videoId_ != null) hash ^= VideoId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (videoId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VideoId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (videoId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VideoId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RecordPlaybackStartedRequest other) {
      if (other == null) {
        return;
      }
      if (other.videoId_ != null) {
        if (videoId_ == null) {
          videoId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        VideoId.MergeFrom(other.VideoId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (videoId_ == null) {
              videoId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(videoId_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Response when recording that a user started playing back a video
  /// </summary>
  public sealed partial class RecordPlaybackStartedResponse : pb::IMessage<RecordPlaybackStartedResponse> {
    private static readonly pb::MessageParser<RecordPlaybackStartedResponse> _parser = new pb::MessageParser<RecordPlaybackStartedResponse>(() => new RecordPlaybackStartedResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RecordPlaybackStartedResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Statistics.StatisticsServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecordPlaybackStartedResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecordPlaybackStartedResponse(RecordPlaybackStartedResponse other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecordPlaybackStartedResponse Clone() {
      return new RecordPlaybackStartedResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RecordPlaybackStartedResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RecordPlaybackStartedResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RecordPlaybackStartedResponse other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  /// <summary>
  ///  Request for getting the number of times a video or set of videos has been played back
  /// </summary>
  public sealed partial class GetNumberOfPlaysRequest : pb::IMessage<GetNumberOfPlaysRequest> {
    private static readonly pb::MessageParser<GetNumberOfPlaysRequest> _parser = new pb::MessageParser<GetNumberOfPlaysRequest>(() => new GetNumberOfPlaysRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetNumberOfPlaysRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Statistics.StatisticsServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetNumberOfPlaysRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetNumberOfPlaysRequest(GetNumberOfPlaysRequest other) : this() {
      videoIds_ = other.videoIds_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetNumberOfPlaysRequest Clone() {
      return new GetNumberOfPlaysRequest(this);
    }

    /// <summary>Field number for the "video_ids" field.</summary>
    public const int VideoIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::KillrVideo.Protobuf.Uuid> _repeated_videoIds_codec
        = pb::FieldCodec.ForMessage(10, global::KillrVideo.Protobuf.Uuid.Parser);
    private readonly pbc::RepeatedField<global::KillrVideo.Protobuf.Uuid> videoIds_ = new pbc::RepeatedField<global::KillrVideo.Protobuf.Uuid>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::KillrVideo.Protobuf.Uuid> VideoIds {
      get { return videoIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetNumberOfPlaysRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetNumberOfPlaysRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!videoIds_.Equals(other.videoIds_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= videoIds_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      videoIds_.WriteTo(output, _repeated_videoIds_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += videoIds_.CalculateSize(_repeated_videoIds_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetNumberOfPlaysRequest other) {
      if (other == null) {
        return;
      }
      videoIds_.Add(other.videoIds_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            videoIds_.AddEntriesFrom(input, _repeated_videoIds_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Response when getting playback stats for a video or set of videos
  /// </summary>
  public sealed partial class GetNumberOfPlaysResponse : pb::IMessage<GetNumberOfPlaysResponse> {
    private static readonly pb::MessageParser<GetNumberOfPlaysResponse> _parser = new pb::MessageParser<GetNumberOfPlaysResponse>(() => new GetNumberOfPlaysResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetNumberOfPlaysResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Statistics.StatisticsServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetNumberOfPlaysResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetNumberOfPlaysResponse(GetNumberOfPlaysResponse other) : this() {
      stats_ = other.stats_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetNumberOfPlaysResponse Clone() {
      return new GetNumberOfPlaysResponse(this);
    }

    /// <summary>Field number for the "stats" field.</summary>
    public const int StatsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::KillrVideo.Statistics.PlayStats> _repeated_stats_codec
        = pb::FieldCodec.ForMessage(10, global::KillrVideo.Statistics.PlayStats.Parser);
    private readonly pbc::RepeatedField<global::KillrVideo.Statistics.PlayStats> stats_ = new pbc::RepeatedField<global::KillrVideo.Statistics.PlayStats>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::KillrVideo.Statistics.PlayStats> Stats {
      get { return stats_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetNumberOfPlaysResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetNumberOfPlaysResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!stats_.Equals(other.stats_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= stats_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      stats_.WriteTo(output, _repeated_stats_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += stats_.CalculateSize(_repeated_stats_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetNumberOfPlaysResponse other) {
      if (other == null) {
        return;
      }
      stats_.Add(other.stats_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            stats_.AddEntriesFrom(input, _repeated_stats_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  The playback stats for a given video id
  /// </summary>
  public sealed partial class PlayStats : pb::IMessage<PlayStats> {
    private static readonly pb::MessageParser<PlayStats> _parser = new pb::MessageParser<PlayStats>(() => new PlayStats());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayStats> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Statistics.StatisticsServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayStats() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayStats(PlayStats other) : this() {
      VideoId = other.videoId_ != null ? other.VideoId.Clone() : null;
      views_ = other.views_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayStats Clone() {
      return new PlayStats(this);
    }

    /// <summary>Field number for the "video_id" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private global::KillrVideo.Protobuf.Uuid videoId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::KillrVideo.Protobuf.Uuid VideoId {
      get { return videoId_; }
      set {
        videoId_ = value;
      }
    }

    /// <summary>Field number for the "views" field.</summary>
    public const int ViewsFieldNumber = 2;
    private long views_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Views {
      get { return views_; }
      set {
        views_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayStats);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayStats other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VideoId, other.VideoId)) return false;
      if (Views != other.Views) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (videoId_ != null) hash ^= VideoId.GetHashCode();
      if (Views != 0L) hash ^= Views.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (videoId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VideoId);
      }
      if (Views != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Views);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (videoId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VideoId);
      }
      if (Views != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Views);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayStats other) {
      if (other == null) {
        return;
      }
      if (other.videoId_ != null) {
        if (videoId_ == null) {
          videoId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        VideoId.MergeFrom(other.VideoId);
      }
      if (other.Views != 0L) {
        Views = other.Views;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (videoId_ == null) {
              videoId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(videoId_);
            break;
          }
          case 16: {
            Views = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
