// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search/search_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace KillrVideo.Search {

  /// <summary>Holder for reflection information generated from search/search_service.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class SearchServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for search/search_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SearchServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtzZWFyY2gvc2VhcmNoX3NlcnZpY2UucHJvdG8SEWtpbGxydmlkZW8uc2Vh",
            "cmNoGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGhljb21tb24v",
            "Y29tbW9uX3R5cGVzLnByb3RvIk0KE1NlYXJjaFZpZGVvc1JlcXVlc3QSDQoF",
            "cXVlcnkYASABKAkSEQoJcGFnZV9zaXplGAIgASgFEhQKDHBhZ2luZ19zdGF0",
            "ZRgQIAEoCSJ5ChRTZWFyY2hWaWRlb3NSZXNwb25zZRINCgVxdWVyeRgBIAEo",
            "CRI8CgZ2aWRlb3MYAiADKAsyLC5raWxscnZpZGVvLnNlYXJjaC5TZWFyY2hS",
            "ZXN1bHRzVmlkZW9QcmV2aWV3EhQKDHBhZ2luZ19zdGF0ZRgDIAEoCSLOAQoZ",
            "U2VhcmNoUmVzdWx0c1ZpZGVvUHJldmlldxIpCgh2aWRlb19pZBgBIAEoCzIX",
            "LmtpbGxydmlkZW8uY29tbW9uLlV1aWQSLgoKYWRkZWRfZGF0ZRgCIAEoCzIa",
            "Lmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDAoEbmFtZRgDIAEoCRIeChZw",
            "cmV2aWV3X2ltYWdlX2xvY2F0aW9uGAQgASgJEigKB3VzZXJfaWQYBSABKAsy",
            "Fy5raWxscnZpZGVvLmNvbW1vbi5VdWlkIj4KGkdldFF1ZXJ5U3VnZ2VzdGlv",
            "bnNSZXF1ZXN0Eg0KBXF1ZXJ5GAEgASgJEhEKCXBhZ2Vfc2l6ZRgCIAEoBSJB",
            "ChtHZXRRdWVyeVN1Z2dlc3Rpb25zUmVzcG9uc2USDQoFcXVlcnkYASABKAkS",
            "EwoLc3VnZ2VzdGlvbnMYAiADKAky5gEKDVNlYXJjaFNlcnZpY2USXwoMU2Vh",
            "cmNoVmlkZW9zEiYua2lsbHJ2aWRlby5zZWFyY2guU2VhcmNoVmlkZW9zUmVx",
            "dWVzdBonLmtpbGxydmlkZW8uc2VhcmNoLlNlYXJjaFZpZGVvc1Jlc3BvbnNl",
            "EnQKE0dldFF1ZXJ5U3VnZ2VzdGlvbnMSLS5raWxscnZpZGVvLnNlYXJjaC5H",
            "ZXRRdWVyeVN1Z2dlc3Rpb25zUmVxdWVzdBouLmtpbGxydmlkZW8uc2VhcmNo",
            "LkdldFF1ZXJ5U3VnZ2VzdGlvbnNSZXNwb25zZUIUqgIRS2lsbHJWaWRlby5T",
            "ZWFyY2hiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::KillrVideo.Protobuf.CommonTypesReflection.Descriptor, },
          new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.Search.SearchVideosRequest), global::KillrVideo.Search.SearchVideosRequest.Parser, new[]{ "Query", "PageSize", "PagingState" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.Search.SearchVideosResponse), global::KillrVideo.Search.SearchVideosResponse.Parser, new[]{ "Query", "Videos", "PagingState" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.Search.SearchResultsVideoPreview), global::KillrVideo.Search.SearchResultsVideoPreview.Parser, new[]{ "VideoId", "AddedDate", "Name", "PreviewImageLocation", "UserId" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.Search.GetQuerySuggestionsRequest), global::KillrVideo.Search.GetQuerySuggestionsRequest.Parser, new[]{ "Query", "PageSize" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::KillrVideo.Search.GetQuerySuggestionsResponse), global::KillrVideo.Search.GetQuerySuggestionsResponse.Parser, new[]{ "Query", "Suggestions" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  Request when searching for videos by a query term
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class SearchVideosRequest : pb::IMessage<SearchVideosRequest> {
    private static readonly pb::MessageParser<SearchVideosRequest> _parser = new pb::MessageParser<SearchVideosRequest>(() => new SearchVideosRequest());
    public static pb::MessageParser<SearchVideosRequest> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Search.SearchServiceReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public SearchVideosRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    public SearchVideosRequest(SearchVideosRequest other) : this() {
      query_ = other.query_;
      pageSize_ = other.pageSize_;
      pagingState_ = other.pagingState_;
    }

    public SearchVideosRequest Clone() {
      return new SearchVideosRequest(this);
    }

    /// <summary>Field number for the "query" field.</summary>
    public const int QueryFieldNumber = 1;
    private string query_ = "";
    public string Query {
      get { return query_; }
      set {
        query_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "page_size" field.</summary>
    public const int PageSizeFieldNumber = 2;
    private int pageSize_;
    public int PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    /// <summary>Field number for the "paging_state" field.</summary>
    public const int PagingStateFieldNumber = 16;
    private string pagingState_ = "";
    public string PagingState {
      get { return pagingState_; }
      set {
        pagingState_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as SearchVideosRequest);
    }

    public bool Equals(SearchVideosRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Query != other.Query) return false;
      if (PageSize != other.PageSize) return false;
      if (PagingState != other.PagingState) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Query.Length != 0) hash ^= Query.GetHashCode();
      if (PageSize != 0) hash ^= PageSize.GetHashCode();
      if (PagingState.Length != 0) hash ^= PagingState.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Query.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Query);
      }
      if (PageSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PageSize);
      }
      if (PagingState.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(PagingState);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Query.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Query);
      }
      if (PageSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageSize);
      }
      if (PagingState.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PagingState);
      }
      return size;
    }

    public void MergeFrom(SearchVideosRequest other) {
      if (other == null) {
        return;
      }
      if (other.Query.Length != 0) {
        Query = other.Query;
      }
      if (other.PageSize != 0) {
        PageSize = other.PageSize;
      }
      if (other.PagingState.Length != 0) {
        PagingState = other.PagingState;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Query = input.ReadString();
            break;
          }
          case 16: {
            PageSize = input.ReadInt32();
            break;
          }
          case 130: {
            PagingState = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Response when searching for videos
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class SearchVideosResponse : pb::IMessage<SearchVideosResponse> {
    private static readonly pb::MessageParser<SearchVideosResponse> _parser = new pb::MessageParser<SearchVideosResponse>(() => new SearchVideosResponse());
    public static pb::MessageParser<SearchVideosResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Search.SearchServiceReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public SearchVideosResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public SearchVideosResponse(SearchVideosResponse other) : this() {
      query_ = other.query_;
      videos_ = other.videos_.Clone();
      pagingState_ = other.pagingState_;
    }

    public SearchVideosResponse Clone() {
      return new SearchVideosResponse(this);
    }

    /// <summary>Field number for the "query" field.</summary>
    public const int QueryFieldNumber = 1;
    private string query_ = "";
    public string Query {
      get { return query_; }
      set {
        query_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "videos" field.</summary>
    public const int VideosFieldNumber = 2;
    private static readonly pb::FieldCodec<global::KillrVideo.Search.SearchResultsVideoPreview> _repeated_videos_codec
        = pb::FieldCodec.ForMessage(18, global::KillrVideo.Search.SearchResultsVideoPreview.Parser);
    private readonly pbc::RepeatedField<global::KillrVideo.Search.SearchResultsVideoPreview> videos_ = new pbc::RepeatedField<global::KillrVideo.Search.SearchResultsVideoPreview>();
    public pbc::RepeatedField<global::KillrVideo.Search.SearchResultsVideoPreview> Videos {
      get { return videos_; }
    }

    /// <summary>Field number for the "paging_state" field.</summary>
    public const int PagingStateFieldNumber = 3;
    private string pagingState_ = "";
    public string PagingState {
      get { return pagingState_; }
      set {
        pagingState_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as SearchVideosResponse);
    }

    public bool Equals(SearchVideosResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Query != other.Query) return false;
      if(!videos_.Equals(other.videos_)) return false;
      if (PagingState != other.PagingState) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Query.Length != 0) hash ^= Query.GetHashCode();
      hash ^= videos_.GetHashCode();
      if (PagingState.Length != 0) hash ^= PagingState.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Query.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Query);
      }
      videos_.WriteTo(output, _repeated_videos_codec);
      if (PagingState.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PagingState);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Query.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Query);
      }
      size += videos_.CalculateSize(_repeated_videos_codec);
      if (PagingState.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PagingState);
      }
      return size;
    }

    public void MergeFrom(SearchVideosResponse other) {
      if (other == null) {
        return;
      }
      if (other.Query.Length != 0) {
        Query = other.Query;
      }
      videos_.Add(other.videos_);
      if (other.PagingState.Length != 0) {
        PagingState = other.PagingState;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Query = input.ReadString();
            break;
          }
          case 18: {
            videos_.AddEntriesFrom(input, _repeated_videos_codec);
            break;
          }
          case 26: {
            PagingState = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  A video preview returned in search results
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class SearchResultsVideoPreview : pb::IMessage<SearchResultsVideoPreview> {
    private static readonly pb::MessageParser<SearchResultsVideoPreview> _parser = new pb::MessageParser<SearchResultsVideoPreview>(() => new SearchResultsVideoPreview());
    public static pb::MessageParser<SearchResultsVideoPreview> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Search.SearchServiceReflection.Descriptor.MessageTypes[2]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public SearchResultsVideoPreview() {
      OnConstruction();
    }

    partial void OnConstruction();

    public SearchResultsVideoPreview(SearchResultsVideoPreview other) : this() {
      VideoId = other.videoId_ != null ? other.VideoId.Clone() : null;
      AddedDate = other.addedDate_ != null ? other.AddedDate.Clone() : null;
      name_ = other.name_;
      previewImageLocation_ = other.previewImageLocation_;
      UserId = other.userId_ != null ? other.UserId.Clone() : null;
    }

    public SearchResultsVideoPreview Clone() {
      return new SearchResultsVideoPreview(this);
    }

    /// <summary>Field number for the "video_id" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private global::KillrVideo.Protobuf.Uuid videoId_;
    public global::KillrVideo.Protobuf.Uuid VideoId {
      get { return videoId_; }
      set {
        videoId_ = value;
      }
    }

    /// <summary>Field number for the "added_date" field.</summary>
    public const int AddedDateFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp addedDate_;
    public global::Google.Protobuf.WellKnownTypes.Timestamp AddedDate {
      get { return addedDate_; }
      set {
        addedDate_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    public string Name {
      get { return name_; }
      set {
        name_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "preview_image_location" field.</summary>
    public const int PreviewImageLocationFieldNumber = 4;
    private string previewImageLocation_ = "";
    public string PreviewImageLocation {
      get { return previewImageLocation_; }
      set {
        previewImageLocation_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 5;
    private global::KillrVideo.Protobuf.Uuid userId_;
    public global::KillrVideo.Protobuf.Uuid UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as SearchResultsVideoPreview);
    }

    public bool Equals(SearchResultsVideoPreview other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VideoId, other.VideoId)) return false;
      if (!object.Equals(AddedDate, other.AddedDate)) return false;
      if (Name != other.Name) return false;
      if (PreviewImageLocation != other.PreviewImageLocation) return false;
      if (!object.Equals(UserId, other.UserId)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (videoId_ != null) hash ^= VideoId.GetHashCode();
      if (addedDate_ != null) hash ^= AddedDate.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (PreviewImageLocation.Length != 0) hash ^= PreviewImageLocation.GetHashCode();
      if (userId_ != null) hash ^= UserId.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (videoId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VideoId);
      }
      if (addedDate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AddedDate);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (PreviewImageLocation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PreviewImageLocation);
      }
      if (userId_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(UserId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (videoId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VideoId);
      }
      if (addedDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AddedDate);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (PreviewImageLocation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PreviewImageLocation);
      }
      if (userId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserId);
      }
      return size;
    }

    public void MergeFrom(SearchResultsVideoPreview other) {
      if (other == null) {
        return;
      }
      if (other.videoId_ != null) {
        if (videoId_ == null) {
          videoId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        VideoId.MergeFrom(other.VideoId);
      }
      if (other.addedDate_ != null) {
        if (addedDate_ == null) {
          addedDate_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        AddedDate.MergeFrom(other.AddedDate);
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.PreviewImageLocation.Length != 0) {
        PreviewImageLocation = other.PreviewImageLocation;
      }
      if (other.userId_ != null) {
        if (userId_ == null) {
          userId_ = new global::KillrVideo.Protobuf.Uuid();
        }
        UserId.MergeFrom(other.UserId);
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (videoId_ == null) {
              videoId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(videoId_);
            break;
          }
          case 18: {
            if (addedDate_ == null) {
              addedDate_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(addedDate_);
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            PreviewImageLocation = input.ReadString();
            break;
          }
          case 42: {
            if (userId_ == null) {
              userId_ = new global::KillrVideo.Protobuf.Uuid();
            }
            input.ReadMessage(userId_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Request for getting query suggestions based on some user input
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GetQuerySuggestionsRequest : pb::IMessage<GetQuerySuggestionsRequest> {
    private static readonly pb::MessageParser<GetQuerySuggestionsRequest> _parser = new pb::MessageParser<GetQuerySuggestionsRequest>(() => new GetQuerySuggestionsRequest());
    public static pb::MessageParser<GetQuerySuggestionsRequest> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Search.SearchServiceReflection.Descriptor.MessageTypes[3]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GetQuerySuggestionsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GetQuerySuggestionsRequest(GetQuerySuggestionsRequest other) : this() {
      query_ = other.query_;
      pageSize_ = other.pageSize_;
    }

    public GetQuerySuggestionsRequest Clone() {
      return new GetQuerySuggestionsRequest(this);
    }

    /// <summary>Field number for the "query" field.</summary>
    public const int QueryFieldNumber = 1;
    private string query_ = "";
    public string Query {
      get { return query_; }
      set {
        query_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "page_size" field.</summary>
    public const int PageSizeFieldNumber = 2;
    private int pageSize_;
    public int PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GetQuerySuggestionsRequest);
    }

    public bool Equals(GetQuerySuggestionsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Query != other.Query) return false;
      if (PageSize != other.PageSize) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Query.Length != 0) hash ^= Query.GetHashCode();
      if (PageSize != 0) hash ^= PageSize.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Query.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Query);
      }
      if (PageSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PageSize);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Query.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Query);
      }
      if (PageSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageSize);
      }
      return size;
    }

    public void MergeFrom(GetQuerySuggestionsRequest other) {
      if (other == null) {
        return;
      }
      if (other.Query.Length != 0) {
        Query = other.Query;
      }
      if (other.PageSize != 0) {
        PageSize = other.PageSize;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Query = input.ReadString();
            break;
          }
          case 16: {
            PageSize = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Response with top query suggestions for the user input 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GetQuerySuggestionsResponse : pb::IMessage<GetQuerySuggestionsResponse> {
    private static readonly pb::MessageParser<GetQuerySuggestionsResponse> _parser = new pb::MessageParser<GetQuerySuggestionsResponse>(() => new GetQuerySuggestionsResponse());
    public static pb::MessageParser<GetQuerySuggestionsResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::KillrVideo.Search.SearchServiceReflection.Descriptor.MessageTypes[4]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GetQuerySuggestionsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GetQuerySuggestionsResponse(GetQuerySuggestionsResponse other) : this() {
      query_ = other.query_;
      suggestions_ = other.suggestions_.Clone();
    }

    public GetQuerySuggestionsResponse Clone() {
      return new GetQuerySuggestionsResponse(this);
    }

    /// <summary>Field number for the "query" field.</summary>
    public const int QueryFieldNumber = 1;
    private string query_ = "";
    public string Query {
      get { return query_; }
      set {
        query_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "suggestions" field.</summary>
    public const int SuggestionsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_suggestions_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> suggestions_ = new pbc::RepeatedField<string>();
    public pbc::RepeatedField<string> Suggestions {
      get { return suggestions_; }
    }

    public override bool Equals(object other) {
      return Equals(other as GetQuerySuggestionsResponse);
    }

    public bool Equals(GetQuerySuggestionsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Query != other.Query) return false;
      if(!suggestions_.Equals(other.suggestions_)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Query.Length != 0) hash ^= Query.GetHashCode();
      hash ^= suggestions_.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Query.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Query);
      }
      suggestions_.WriteTo(output, _repeated_suggestions_codec);
    }

    public int CalculateSize() {
      int size = 0;
      if (Query.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Query);
      }
      size += suggestions_.CalculateSize(_repeated_suggestions_codec);
      return size;
    }

    public void MergeFrom(GetQuerySuggestionsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Query.Length != 0) {
        Query = other.Query;
      }
      suggestions_.Add(other.suggestions_);
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Query = input.ReadString();
            break;
          }
          case 18: {
            suggestions_.AddEntriesFrom(input, _repeated_suggestions_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
